[package]
name = "yew-macros"
version = "0.0.1"
edition = "2018"

[workspace]

[[bin]]
name = "macros"
path = "main.rs"

[dependencies]
yew-html = { path = "html" }
yew-html-impl = { path = "html-impl" }
