[package]
name = "yew-html-common"
version = "0.0.1"
edition = "2018"

[dependencies]
boolinator = "2.4.0"
syn = { version = "0.15", features = ["full"] }
quote = "0.6"
proc-macro-hack = "0.5"
proc-macro2 = "0.4"
